export interface Receipt {
  id: string;
  receiptNumber: string;
  tenantId: string;
  tenantName: string;
  tenantEmail: string;
  tenantPhone: string;
  propertyId: string;
  propertyName: string;
  roomId?: string;
  roomName?: string;
  ownerId?: string;
  ownerName?: string;
  ownerEmail?: string;
  ownerPhone?: string;
  isColocation: boolean;
  colocataires?: ReceiptColocation[];
  totalAmount: number;
  amount: number;
  paymentDate: Date;
  paymentMethod: 'cash' | 'bank_transfer' | 'mobile_money' | 'check';
  reference?: string;
  periodStart: Date;
  periodEnd: Date;
  status: 'paid' | 'partial' | 'pending';
  templateId?: string;
  autoGenerated: boolean;
  sentAt?: Date;
  sentChannels?: ('email' | 'whatsapp' | 'sms')[];
  createdAt: Date;
  updatedAt: Date;
}

export interface ReceiptFilters {
  propertyId?: string;
  roomId?: string;
  tenantId?: string;
  ownerId?: string;
  startDate?: Date;
  endDate?: Date;
  status?: Receipt['status'];
}

export interface ReceiptTemplate {
  id: string;
  name: string;
  agencyName: string;
  agencyAddress: string;
  agencyPhone: string;
  agencyEmail: string;
  agencyLogo?: string;
  headerColor: string;
  footerText: string;
  showSignature: boolean;
  showWatermark: boolean;
  customTerms?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ReceiptColocation {
  receiptId: string;
  tenantId: string;
  tenantName: string;
  tenantEmail: string;
  tenantPhone: string;
  amount: number;
  sharePercentage?: number;
  isPrimaryTenant: boolean;
}

export interface ReceiptOwner {
  ownerId: string;
  ownerName: string;
  ownerEmail: string;
  ownerPhone: string;
  commissionPercentage?: number;
  commissionAmount?: number;
}

export interface ReceiptAutoGenerationConfig {
  enabled: boolean;
  generateOnPayment: boolean;
  sendToTenant: boolean;
  sendToOwner: boolean;
  channels: ('email' | 'whatsapp' | 'sms')[];
  gracePeriodDays: number;
  autoSendDelay: number; // en heures
}

export interface ReceiptGenerationRequest {
  tenantId: string;
  propertyId: string;
  roomId?: string;
  amount: number;
  paymentMethod: Receipt['paymentMethod'];
  reference?: string;
  periodMonth: number;
  periodYear: number;
}

export interface BulkReceiptGeneration {
  filter: ReceiptFilters;
  recipients: ('email' | 'whatsapp' | 'sms')[];
}

export interface ReceiptStats {
  totalCollected: number;
  pendingAmount: number;
  receiptsCount: number;
  averageRent: number;
}
